src/StatusReports/ViewModels/StatusReportViewModel.cs
using StatusReports.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StatusReports.ViewModels
{
    public class StatusReportViewModel
    {
        public StatusReportViewModel()
        { }
        public StatusReportViewModel(IndividualStatusReport statusReport, LookupModel lookupData)
        {
            StatusReport = statusReport;
            LookupData = lookupData;
        }
        public IndividualStatusReport StatusReport { get; set; }
        public LookupModel LookupData { get; set; }
    }
}

src/StatusReports/Controllers/StatusReportController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using StatusReports.Models;
using System.Threading.Tasks;
using System;
using StatusReports.Data;
using System.Collections.Generic;
using StatusReports.ViewModels;

namespace StatusReports.Controllers
{
    public class StatusReportController : Controller
    {
        private IRepository<IndividualStatusReport> statusReportRepo;

        public StatusReportController(IRepository<IndividualStatusReport> statusReportRepo)
        {
            this.statusReportRepo = statusReportRepo;
        }

        // GET: IndividualStatus
        public async Task<IActionResult> Index()
        {
            var lookupData = await statusReportRepo.GetLookupDataAsync();
            return View(new StatusReportViewModel(null, lookupData));
        }

        // GET: IndividualStatus/Create
        public async Task<IActionResult> Create()
        {
            var lookupData = await statusReportRepo.GetLookupDataAsync();
            return View(new StatusReportViewModel(null, lookupData));
        }

        // POST: IndividualStatus/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StatusReportViewModel StatusReportVM, string save, string completed)
        {
            var lookupData = await statusReportRepo.GetLookupDataAsync();
            if (ModelState.IsValid)
            {
                //TODO: refactor to void performance hit by re-getting the date
                var weekSelected = DateTime.Parse(lookupData.Weeks.FirstOrDefault(c => c.LookupId == StatusReportVM.StatusReport.WeekId).LookupValue);

                for (int i = 0; i < StatusReportVM.StatusReport.IndividualStatusItems.Count; i++)
                {
                    var daysToSubtract = new TimeSpan(6 - i, 0, 0, 0);
                    StatusReportVM.StatusReport.IndividualStatusItems[i].Date = weekSelected.Subtract(daysToSubtract);
                }

                //the user can create a status report and directly submit it to PM
                if (!string.IsNullOrEmpty(save))
                {
                    StatusReportVM.StatusReport.Status = StatusCode.Draft;
                }
                if (!string.IsNullOrEmpty(completed))
                {
                    StatusReportVM.StatusReport.Status = StatusCode.Submitted;
                }

                await statusReportRepo.AddAndSaveAsync(StatusReportVM.StatusReport);
                return RedirectToAction("Index");
            }
            else
            {
                //TODO: in case of invalid state, alert the user
            }

            return View(new StatusReportViewModel(StatusReportVM.StatusReport, lookupData));
        }

        // GET: IndividualStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var statusRprt = await statusReportRepo.GetByIdAsync(id.Value);
            if (statusRprt == null)
            {
                return HttpNotFound();
            }

            //TODO: to be revised
            statusRprt.IndividualStatusItems = statusRprt.IndividualStatusItems.OrderBy(c => c.Date).ToList();

            return View(statusRprt);
        }

        // POST: IndividualStatus/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IndividualStatusReport individualStatusReport, string save, string completed)
        {
            if (ModelState.IsValid)
            {
                //Save the changes
                if (!string.IsNullOrEmpty(save))
                {
                    individualStatusReport.Status = StatusCode.Draft;
                }
                if (!string.IsNullOrEmpty(completed))
                {
                    individualStatusReport.Status = StatusCode.Submitted;
                }

                //Update the database
                statusReportRepo.UpdateAndSaveAsync(individualStatusReport);
                return RedirectToAction("Index");
            }

            return View(individualStatusReport);
        }

    }
}

src/StatusReports/ViewComponents/StatusReportsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using StatusReports.Models;
using StatusReports.Data;
using Microsoft.Data.Entity;
// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace StatusReports.ViewComponents
{
    [ViewComponent(Name = "StatusReports")]
    public class StatusReportsViewComponent : ViewComponent
    {
        private IRepository<IndividualStatusReport> statusReportRepo;

        public StatusReportsViewComponent(IRepository<IndividualStatusReport> statusReportRepo)
        {
            this.statusReportRepo = statusReportRepo;
        }

        public async Task<IViewComponentResult> InvokeAsync(StatusCode status)
        {
            return View(await GetStatusReports(status));
        }

        private async Task<List<IndividualStatusReport>> GetStatusReports(StatusCode status)
        {
            return await statusReportRepo.GetAll().Include(i => i.Person)
                                                   .Include(i => i.Project).ThenInclude(c => c.Client)
                                                   .Include(i => i.Week)
                                                   .Include(i => i.IndividualStatusItems)
                                                   .Where(i => i.Status == status)
                                                   .ToListAsync();
        }
    }
}

src/StatusReports/Views/StatusReport/Create.cshtml
@model StatusReports.ViewModels.StatusReportViewModel

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-center">Add New Status Report</h2>
<hr/>
<form asp-action="Create" id="createForm">
    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
    @*<hr />*@
 <div class="form-horizontal">
     <div class="row">
         <div class="form-group col-md-4">
             <label asp-for="StatusReport.PersonId" class="col-md-4 control-label"></label>
             <div class="col-md-8">
                 <select asp-for="StatusReport.PersonId" asp-items="@(new SelectList( Model.LookupData.People, "LookupId", "LookupValue", Model.StatusReport?.PersonId ))" class="form-control"></select>
             </div>
         </div>
         <div class="form-group col-md-4">
             <label asp-for="StatusReport.ProjectId" class="col-md-4 control-label"></label>
             <div class="col-md-8">
                 <select asp-for="StatusReport.ProjectId" asp-items="@(new SelectList( Model.LookupData.Projects, "LookupId", "LookupValue", Model.StatusReport?.ProjectId ))" class="form-control"></select>
             </div>
         </div>
         <div class="form-group col-md-4">
             <label asp-for="StatusReport.WeekId" class="col-md-4 control-label"></label>
             <div class="col-md-8">
                 <select asp-for="StatusReport.WeekId" asp-items="@(new SelectList( Model.LookupData.Weeks, "LookupId", "LookupValue", Model.StatusReport?.WeekId ))" class="form-control"></select>
             </div>
         </div>
         
     </div>
        <div class="col-sm-12">
            <div class="list-group statusTable">
                <div class="col-sm-12 list-group-item active">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-2 text-center"><strong>Hours</strong></div>
                    <div class="col-sm-8 text-center"><strong>Work Description</strong></div>
                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Saturday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[0].Date" value="" />
                    </label>
                    <div class="col-sm-2 ">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[0].Hours" class="text-center form-control" 
                               value="0" min="0" max="24" required />
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[0].WorkDescription" placeholder="description"></textarea>
                    </div>
                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Sunday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[1].Date" value="" />
                    </label>
                    <div class="col-sm-2">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[1].Hours" class="text-center form-control" min="0" max="24" value="0" required/>
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[1].WorkDescription" placeholder="description"></textarea>
                    </div>
                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Monday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[2].Date" value="" />
                    </label>
                    <div class="col-sm-2">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[2].Hours" min="0" max="24" class="text-center form-control" value="0" required/>
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[2].WorkDescription" placeholder="description"></textarea>
                    </div>

                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Tuesday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[3].Date" value="" />
                    </label>
                    <div class="col-sm-2">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[3].Hours" class="text-center form-control" min="0" max="24" value="0" required/>
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[3].WorkDescription" placeholder="description"></textarea>
                    </div>
                    
                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Wednesday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[4].Date" value="" />
                    </label>
                    <div class="col-sm-2">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[4].Hours" class="text-center form-control" 
                               min="0" max="24" value="0" />
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[4].WorkDescription" placeholder="description"></textarea>
                    </div>
                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Thursday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[5].Date" value="" />
                    </label>
                    <div class="col-sm-2">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[5].Hours" class="text-center form-control" value="0" required/>
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[5].WorkDescription" placeholder="description"></textarea>
                    </div>
                </div>
                <div class="col-sm-12 list-group-item">
                    <label class="col-sm-2 control-label">
                        Friday
                        <input type="hidden" name="StatusReport.IndividualStatusItems[6].Date" value="" />
                    </label>
                    <div class="col-sm-2">
                        <input type="number" disabled name="StatusReport.IndividualStatusItems[6].Hours" class="text-center form-control" value="0" />
                    </div>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="StatusReport.IndividualStatusItems[6].WorkDescription" placeholder="description"></textarea>
                        <input name="lostSon" type="hidden" value="hiddenTruth" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row form-group">
            <div class="row text-center">
                <input type="submit" value="Save As Draft" name="save" class="btn btn-primary" />
                <input type="submit" value="Submit To PM" name="completed" class="btn btn-danger"  />
            </div>
        </div>
    </div>
</form>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/StatusReports/Views/StatusReport/Edit.cshtml
@model StatusReports.Models.IndividualStatusReport

@{
    ViewData["Title"] = "Update";
}

<h2 class="text-center">Update Status Report</h2>
<hr />
<form asp-action="Edit" id="editForm">
    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
    <div class="form-horizontal">
        <div class="row">
            <div class="form-group col-md-4">
                <label class="col-md-4 control-label">Name:</label>
                <div class="col-md-8">
                    <label class="form-control">@Model.Person.FullName</label>
                    <input type="hidden" asp-for="PersonId" value="@Model.PersonId" />
                </div>
            </div>
            <div class="form-group col-md-4">
                <label class="col-md-4 control-label">Project:</label>
                <div class="col-md-8">
                    <label class="form-control">@Model.Project.Name</label>
                    <input type="hidden" asp-for="ProjectId" value="@Model.ProjectId" />
                </div>
            </div>
            <div class="form-group col-md-4">
                <label class="col-md-4 control-label">Week:</label>
                <div class="col-md-8">
                    <label class="form-control">@Model.Week.EndingDate.ToString("MM/dd/yyyy")</label>
                    <input type="hidden" asp-for="WeekId" value="@Model.WeekId" />

                </div>
            </div>
        </div>
        <br />
     \
        <div class="col-sm-12">
            <div class="list-group statusTable">
                <div class="col-sm-12 list-group-item active">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-2 text-center"><strong>Hours</strong></div>
                    <div class="col-sm-8 text-center"><strong>Work Description</strong></div>
                </div>
                @for (int i = 0; i < Model.IndividualStatusItems.Count; i++)
                {
                <div class="col-sm-12 list-group-item">

                    <label class="col-sm-2 control-label">
                        @Model.IndividualStatusItems[i].FormattedDay
                        <input type="hidden" name="IndividualStatusItems[@i].Date" value="@Model.IndividualStatusItems[i].Date" />
                        <input type="hidden" name="IndividualStatusItems[@i].Id" value="@Model.IndividualStatusItems[i].Id" />
                    </label>
                    <div class="col-sm-2">
                        <label class="visible-sm">Hours</label>
                        <input type="number" disabled placeholder="hours" name="IndividualStatusItems[@i].Hours" value="@Model.IndividualStatusItems[i].Hours" class="text-center form-control" min="0" max="10" required/>
                    </div>
                    <label class="visible-sm">Description</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="IndividualStatusItems[@i].WorkDescription" placeholder="description">@Model.IndividualStatusItems[i].WorkDescription</textarea>
                    </div>
                </div>
                }
            </div>
        </div>
        <div class="row form-group">
            <div class="row text-center">
                @if (Model.Status == StatusCode.Draft)
                {<!--TODO--> }
                    <input type="submit" value="Save As Draft" name="save" class="btn btn-primary" />
                    <input type="submit" value="Submit To PM" name="completed" class="btn btn-success"/>
                
            </div>
        </div>
    </div>
</form>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/StatusReports/Views/StatusReport/Index.cshtml
@model StatusReports.ViewModels.StatusReportViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="developerHome">
    <div class="text-right">
        <a class="btn btn-primary"   href="@Url.Action("Create","StatusReport" )">New Status Report</a>
    </div>

    <div>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#outstandingDiv" aria-controls="home" role="tab" data-toggle="tab">Outstanding Reports</a>
            </li>
            <li role="presentation">
                <a href="#completedDiv" aria-controls="profile" role="tab" data-toggle="tab">Completed Reports</a>
            </li>
            <li role="presentation">
                <a href="#approvedReports" aria-controls="messages" role="tab" data-toggle="tab">Approved Reports</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="outstandingDiv">
                <h3 class="text-center"> Outstanding Status Reports</h3>
                @await Component.InvokeAsync("StatusReports", StatusCode.Draft)
            </div>
            <div role="tabpanel" class="tab-pane" id="completedDiv">
                <h3 class="text-center"> Completed Status Reports</h3>
                @await Component.InvokeAsync("StatusReports", StatusCode.Submitted)
            </div>
            <div role="tabpanel" class="tab-pane" id="approvedReports">
                <h3 class="text-center"> Approved Status Reports</h3>
                @await Component.InvokeAsync("StatusReports", StatusCode.Approved)
            </div>
        </div>

    </div>
</div>

src/StatusReports/Views/StatusReport/Modal.cshtml
@model StatusReports.Models.IndividualStatusReport

@{
    ViewData["Title"] = "Update";
}
<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<h2 class="text-center">Update Status Report</h2>
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
    <div class="form-horizontal">
        <div class="row">
            <div class="form-group col-md-4">
                <label class="col-md-4 control-label">Name:</label>
                <div class="col-md-8">
                    <label class="form-control">@Model.Person.FullName</label>
                    <input type="hidden" asp-for="PersonId" value="@Model.PersonId" />
                </div>
            </div>
            <div class="form-group col-md-4">
                <label class="col-md-4 control-label">Project:</label>
                <div class="col-md-8">
                    <label class="form-control">@Model.Project.Name</label>
                    <input type="hidden" asp-for="ProjectId" value="@Model.ProjectId" />
                </div>
            </div>
            <div class="form-group col-md-4">
                <label class="col-md-4 control-label">Week:</label>
                <div class="col-md-8">
                    <label class="form-control">@Model.Week.EndingDate.ToString("MM/dd/yyyy")</label>
                    <input type="hidden" asp-for="WeekId" value="@Model.WeekId" />

                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="list-group statusTable col-sm-12">
                <div class="row list-group-item active">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-2 text-center"><strong>Hours</strong></div>
                    <div class="col-sm-8 text-center"><strong>Work Description</strong></div>
                </div>
                @for (int i = 0; i < Model.IndividualStatusItems.Count; i++)
                {
                    <div class="row list-group-item">

                        <label class="col-sm-2 control-label">
                            @Model.IndividualStatusItems[i].FormattedDay
                            <input type="hidden" name="IndividualStatusItems[@i].Date" value="@Model.IndividualStatusItems[i].Date" />
                            <input type="hidden" name="IndividualStatusItems[@i].Id" value="@Model.IndividualStatusItems[i].Id" />
                        </label>
                        <div class="col-sm-2">
                            <input placeholder="hours" name="IndividualStatusItems[@i].Hours" value="@Model.IndividualStatusItems[i].Hours" class="text-center form-control" />
                        </div>
                        <div class="col-sm-8">
                            <textarea class="form-control" name="IndividualStatusItems[@i].WorkDescription" placeholder="description">@Model.IndividualStatusItems[i].WorkDescription</textarea>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="row form-group">
            <div class="row text-center">
                @if (Model.Status == StatusCode.Draft)
                {
                    <input type="submit" value="Save As Draft" name="save" class="btn btn-primary" />
                    <input type="submit" value="Submit To PM" name="completed" class="btn btn-danger" />
                }
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/StatusReports/Views/StatusReport/Submitted.cshtml
@model IEnumerable<StatusReports.Models.IndividualStatusReport>



@foreach (var item in Model.Take(8))
            {
    <div class="panel panel-primary">
        <div class="panel-heading">
            <a style="color:white" href="@Url.Action("Edit","StatusReport", new { item.Id })">@($"{item.Project.Client.Name} - {item.Project.Name}")</a>
        </div>
        <div class="panel-body">
            <p>Week Ending Date: @item.Week.EndingDate.ToString("MM/dd/yyyy")</p>
            <p>Total Hours: @item.IndividualStatusItems?.Sum(c => c.Hours).ToString("#.##")</p>
        </div>
    </div>
}